using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.fs.git.depo._werk_.destiny.be_._ignored._setting
{
	internal class IRules
	{
	}
	internal class IRules_
	{
		/// see <see cref="fs.git.Properties.Resources.ignore4windows"/>, the basis for any depo under windows, excluding some destinations generated by the os, such as icon.db, tmp files.
		///
		///
		/// 
		/// <see cref="fs.git.Properties.Resources.vsSlnIgnore"/> for a dot net solution. ( a sln might be in a project, or in a nonproject folder such as the parent folder of a project.
		///
		/// 
		/// <see cref="fs.git.Properties.Resources.dotNetIgnore"/> for a dot net project
		///
		///
		/// 
		/// <see cref="fs.git.Properties.Resources.nilnulIgnore"/>, for nilnul destinations
		///


	}

}
