//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.fs.git.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svr_vs__prefix {
            get {
                return ((string)(this["svr_vs__prefix"]));
            }
            set {
                this["svr_vs__prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>vs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysVs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysVs"]));
            }
            set {
                this["moduleRemoteKeysVs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>aws</string>\r\n  <string>aw</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysAw {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysAw"]));
            }
            set {
                this["moduleRemoteKeysAw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>bitBucket</string>
  <string>bitbucket</string>
  <string>bb</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysBb {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysBb"]));
            }
            set {
                this["moduleRemoteKeysBb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>gitLab</string>\r\n  <string>gitlab</string>\r\n  <string>gl</string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysGl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysGl"]));
            }
            set {
                this["moduleRemoteKeysGl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>awGlBbVs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysAwGlBbVs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysAwGlBbVs"]));
            }
            set {
                this["moduleRemoteKeysAwGlBbVs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>azure</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemote_azure {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemote_azure"]));
            }
            set {
                this["moduleRemote_azure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svrAzureAcc {
            get {
                return ((string)(this["svrAzureAcc"]));
            }
            set {
                this["svrAzureAcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool upgraded {
            get {
                return ((bool)(this["upgraded"]));
            }
            set {
                this["upgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svr_amazon__region {
            get {
                return ((string)(this["svr_amazon__region"]));
            }
            set {
                this["svr_amazon__region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::nilnul.fs.git.svr.client_.accVaulted.Nameds client__accVaulted_Nameds {
            get {
                return ((global::nilnul.fs.git.svr.client_.accVaulted.Nameds)(this["client__accVaulted_Nameds"]));
            }
            set {
                this["client__accVaulted_Nameds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::nilnul.fs.git.svr.client.repo.sortie_.byHost.biject_.Nom1nonemptyEs clients_pub {
            get {
                return ((global::nilnul.fs.git.svr.client.repo.sortie_.byHost.biject_.Nom1nonemptyEs)(this["clients_pub"]));
            }
            set {
                this["clients_pub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string clients_pub_xml {
            get {
                return ((string)(this["clients_pub_xml"]));
            }
            set {
                this["clients_pub_xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string clients_pub_base6four {
            get {
                return ((string)(this["clients_pub_base6four"]));
            }
            set {
                this["clients_pub_base6four"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::nilnul.fs.git.svr.client_.vaulted.repo.Nameds clients_pub_list {
            get {
                return ((global::nilnul.fs.git.svr.client_.vaulted.repo.Nameds)(this["clients_pub_list"]));
            }
            set {
                this["clients_pub_list"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string clients_pub_dict {
            get {
                return ((string)(this["clients_pub_dict"]));
            }
            set {
                this["clients_pub_dict"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string clients_my_base6four {
            get {
                return ((string)(this["clients_my_base6four"]));
            }
            set {
                this["clients_my_base6four"] = value;
            }
        }
    }
}
