//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.fs.git.svr_._gitlab {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class LimitInMbyte : global::System.Configuration.ApplicationSettingsBase {
        
        private static LimitInMbyte defaultInstance = ((LimitInMbyte)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LimitInMbyte())));
        
        public static LimitInMbyte Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5120")]
        public int repo {
            get {
                return ((int)(this["repo"]));
            }
            set {
                this["repo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5120")]
        public int push {
            get {
                return ((int)(this["push"]));
            }
            set {
                this["push"] = value;
            }
        }
    }
}
