//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.fs.git.depo.repo._setting._descript {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class TheSettings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static TheSettings1 defaultInstance = ((TheSettings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TheSettings1())));
        
        public static TheSettings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unnamed repository; edit this file \'description\' to name the repository.")]
        public string defaultLine {
            get {
                return ((string)(this["defaultLine"]));
            }
            set {
                this["defaultLine"] = value;
            }
        }
    }
}
